// Code generated by MockGen. DO NOT EDIT.
// Source: ../internal/bridge/interface.go
//
// Generated by this command:
//
//	mockgen -destination=../internal/bridge/mocks.go -package=bridge -source=../internal/bridge/interface.go
//
// Package bridge is a generated GoMock package.
package bridge
